### ISSUE TITLE
repop Lord of the dead is 10min late

### ISSUE THREAD

**Issue by S0DA456** [RagnarokMvpTimer/frontend#7]
![image](https://github.com/RagnarokMvpTimer/frontend/assets/144030828/80790b6a-2ef6-45d8-9014-9c2a996d52c6)
timer should be 2:13 instead of 2:23 
![image](https://github.com/RagnarokMvpTimer/frontend/assets/144030828/9b4a8322-2784-4538-8f7b-1d9058f759e7)
(133min = 2h13min)
 :)

**Comment by Lucas8x** [comment]
Yes, you're right, the delay in the respawn was also being included in this timer, really looked strange, now I hope it's better ^^

**Comment by S0DA456** [comment]
it broke every other timer i think
now when when you get to the random timing (10min on most mob) it starts a new timer **from 0 to infinite** in green (and when it's10+min the timer gets in red and label goes from respawning to Already respawn which is good)) instead of going from10 to 0 (till the max respawn time)
![image](https://github.com/RagnarokMvpTimer/frontend/assets/144030828/6c2feaf9-a3a0-4191-8352-fe3eccfad381)
screen doesnt help but it's not a countdown anymore

**Comment by Lucas8x** [comment]
Indeed, I didn't realize, now it'll be normal.
The 10 minutes are fixed, this is the delay that may occur before the mvp actually respawns

**Comment by S0DA456** [comment]
seems good  ! thank you for your reactivity ;)
love your work

**Comment by S0DA456** [comment]
in fact, i just retested, it gives the 10min respawning behavior again on LOD:/
but the timing mechanics was corrected

so it's back to the same as before and LOD is still at 2h13min+10min random delay instead of 2h13min instant repop
